In [2]:
#importing important packages
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
import pandas as pd
from scipy.special import logsumexp

In [3]:
#Total Flow Matrix
R = pd.read_excel(r'/Users/farshidnazemi/Documents/Results.xlsx', sheet_name='Multilayer films',usecols="S:AD", header=198, nrows=12)
R = np.array(R)
R = np.transpose (R)
R = np.float64(R)
R = np.transpose(R)
print (R)

[[0.    0.2   0.    0.    0.    0.    0.    0.011 0.    0.    0.011 0.   ]
 [0.    0.    0.2   0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.2   0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.2   0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.211 0.   ]
 [0.222 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]]


In [4]:
#Internal Flow Matrix (F)
# Get the dimensions of the matrix
rows, cols = R.shape

# Specify how many rows and columns to remove
rows_to_remove = 4
cols_to_remove = 4

# Remove the last rows and columns
if rows_to_remove > 0 and cols_to_remove > 0:
    F = R[:rows - rows_to_remove, :cols - cols_to_remove]
print (F)

[[0.    0.2   0.    0.    0.    0.    0.    0.011]
 [0.    0.    0.2   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.2   0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.2  ]
 [0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.   ]]


In [5]:
#Adjacency matrix (A)
# Create a new matrix with 1 for non-zero elements and 0 for zero elements
A = (F != 0).astype(int)

# Print the resulting matrix
print(A)

[[0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [6]:
#virgin input vector (Z)
# Get the fourth row from the end and store it in a vector
Z = R[-4]
Z = Z[:-4]

# Print the resulting matrix
print(Z)

[0.222 0.    0.    0.    0.    0.    0.    0.   ]


In [7]:
#Recovered input vector (P)
# Get the fourth row from the end and store it in a vector
P = R[-3]
P = P[:-4]
# Print the resulting matrix
print(P)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#Dissipation vector (Y)
# Get the fourth row from the end and store it in a vector
Y = R[:,-2]
Y = Y[:-4]
# Print the resulting matrix
print(Y)

[0.011 0.    0.    0.    0.    0.    0.    0.211]


In [9]:
#Export vector (E)
# Get the fourth row from the end and store it in a vector
E = R[:,-1]
E = E[:-4]
# Print the resulting matrix
print(E)

[0. 0. 0. 0. 0. 0. 0. 0.]


# Structural-based Metrics

In [10]:
#number of compartments
n=len(A)
print ("number of compartments =", n)

number of compartments = 8


In [11]:
#number of links
m=0
for i in range(len(A)):
    for j in range(len(A)):
        if A[i,j]==1:
            m=m+1   
print ("number of links =", m)

number of links = 5


In [12]:
#Link density
L_d = m/n
print ("link density =", L_d)

link density = 0.625


In [13]:
#connectance over direct path
C_d = m/(n**2)
print ("connectance over direct path =", C_d)

connectance over direct path = 0.078125


In [14]:
I = np.identity(n,dtype='float64')
B = np.linalg.inv(I-A)
print(B)

[[1. 1. 1. 1. 0. 0. 0. 2.]
 [0. 1. 1. 1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
#Total number of direct & indirect paths
m_t=0
for i in range(len(B)):
    for j in range(len(B)):
        if B[i,j]!=0:
            m_t = m_t + B[i,j] 
print ("total number of direct & indirect paths =", m_t)

total number of direct & indirect paths = 19.0


In [16]:
#Connectance over all paths
C_t = m_t / n**2
print ("connectance over all paths =", C_t)

connectance over all paths = 0.296875


In [17]:
#pathway proliferation rate
#Find the maximum eigenvalue using NumPy
eigenvalues, eigenvectors = np.linalg.eig(A)
# The eigenvalues array contains the eigenvalues of the matrix
PP = np.max(eigenvalues)
print ("Pathway proliferation rate =", PP)

Pathway proliferation rate = 0.0


In [18]:
#Degree diversity
D = np.sum(A, axis=0)
D_dot = np.sum (D)
DD = 0
epsilon = 1e-10  # A very small number
for i in range(n):
    DD += -((D[i] / (D_dot + epsilon)) * (math.log((D[i] + epsilon) / (D_dot + epsilon), 2)))
print ("degree diversity =", DD)

degree diversity = 1.9219280947623623


# Flow-based Metrics

In [19]:
#Total boundary input
TBI = np.sum(Z) + np.sum(P)
print("Total Boundary Input =", TBI)

Total Boundary Input = 0.222


In [20]:
#Total Internal Flow
TIF = np.sum(F)
print("Total Internal Flow =", TIF)

Total Internal Flow = 0.811


In [21]:
#Total Input (Output) Throughflows
T_i = np.sum(F, axis=0) + Z + P
print("Total Input (Output) Throughflows =", T_i)

Total Input (Output) Throughflows = [0.222 0.2   0.2   0.2   0.    0.    0.    0.211]


In [22]:
#Flow Analysis (identifies non-dimentional flow intensities along indirect pathways)
epsilon = 1e-10
G = F/(T_i + epsilon)

# Configure printing options for NumPy
np.set_printoptions(precision=2, suppress=True)
# Print the matrix in an organized way
print("Non-dimensional flow intensities (G) =")
print(G)

Non-dimensional flow intensities (G) =
[[0.   1.   0.   0.   0.   0.   0.   0.05]
 [0.   0.   1.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.95]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]]


In [23]:
#Dimentionless Integral intensities matrix
I=np.identity(n,dtype='float64')
N=np.linalg.inv(I-G)
# Configure printing options for NumPy
np.set_printoptions(precision=2, suppress=True)
# Print the matrix in an organized way
print("Dimentionless Integral intensities matrix (N) =")
print(N)

Dimentionless Integral intensities matrix (N) =
[[1.   1.   1.   1.   0.   0.   0.   1.  ]
 [0.   1.   1.   1.   0.   0.   0.   0.95]
 [0.   0.   1.   1.   0.   0.   0.   0.95]
 [0.   0.   0.   1.   0.   0.   0.   0.95]
 [0.   0.   0.   0.   1.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   1.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   1.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   1.  ]]


In [24]:
#Utility Analysis
D=np.zeros((n,n),dtype='float64')
for i in range (n):
    for j in range (n):
        D[i,j]=(F[j,i]-F[i,j])/(T_i[i]+epsilon)

# Configure printing options for NumPy
np.set_printoptions(precision=2, suppress=True)
# Print the matrix in an organized way
print("Utility Intensities (D) =")
print(D)

Utility Intensities (D) =
[[ 0.   -0.9   0.    0.    0.    0.    0.   -0.05]
 [ 1.    0.   -1.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    0.   -1.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.   -1.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.05  0.    0.    0.95  0.    0.    0.    0.  ]]


In [25]:
#Utility Intensities
U=np.linalg.inv(I-D)
# Configure printing options for NumPy
np.set_printoptions(precision=2, suppress=True)
# Print the matrix in an organized way
print("Integral Utility Intensities (U) =")
print(U)

Integral Utility Intensities (U) =
[[ 0.65 -0.36  0.23 -0.13  0.    0.    0.    0.1 ]
 [ 0.38  0.39 -0.26  0.13  0.    0.    0.   -0.15]
 [ 0.26  0.25  0.49 -0.26  0.    0.    0.    0.24]
 [ 0.12  0.14  0.25  0.38  0.    0.    0.   -0.39]
 [ 0.    0.    0.    0.    1.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    1.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    1.    0.  ]
 [ 0.15  0.11  0.24  0.36  0.    0.    0.    0.64]]


In [26]:
#Total System Throughflow
TST_flow = np.sum(F)
print("Total System Throughflows (TST_flow) =", TST_flow)

Total System Throughflows (TST_flow) = 0.811


In [27]:
#Total System Throughput
TST_put = np.sum(R)
print("Total System Throughput (TST_put) =", TST_put)

Total System Throughput (TST_put) = 1.2550000000000001


In [28]:
#Average Path Length
APL = TST_flow/(np.sum(Z)+epsilon)
print("Average Path Length (APL) =", APL)

Average Path Length (APL) = 3.653153151507589


In [29]:
#Ratio of direct to indirect flows (I/D)
I_D = np.sum((N-I-G)@T_i)/np.sum(G@T_i)
print("Ratio of direct to indirect flows (I/D) =", I_D)

Ratio of direct to indirect flows (I/D) = 1.4796547460018517


In [30]:
#Indirect effects Index
IEI = I_D/(1+I_D)
print("Indirect effect index (IEI) =", IEI)

Indirect effect index (IEI) = 0.5967180505220008


In [31]:
#Finn's cycling index
#Cycled flow of node i: TSTci
TSTci=np.zeros((n),dtype='float64')
FCI=0.0
for i in range (n):
    TSTci[i]=((N[i,i]-1)/N[i,i])*T_i[i]
for i in range (n):
    FCI=FCI+TSTci[i]/TST_flow
print("Finn's cycling index (FCI) =", FCI)

Finn's cycling index (FCI) = 0.0


In [32]:
#Amplification
AMP = 0
# Iterate through the matrix and count elements larger than 1
for row in N:
    for element in row:
        if element > 1:
            AMP += 1

print("Amplification =", AMP)

Amplification = 0


In [33]:
#Amplification percentage
AMP_per = AMP/(n*(n-1))
print("Amplification percentage =", AMP_per)

Amplification percentage = 0.0


## Utility Analysis 

In [34]:
#Network relationships
m = U.shape[0]
# Create a dictionary to store the relationships
relationships = {}

# Process descriptions
process_descriptions = {
    0: "Product Manufacturer (1)",
    1: "Service Provider (2)",
    2: "User/Consumer (3)",
    3: "Collection (EoL) (4)",
    4: "Reuse (5)",
    5: "Redistribute (EoL) (6)",
    6: "Refurbish/Recycle (EoL) (7)",
    7: "Ultimate EoL (8)"
    
}

# Iterate through each pair of processes
for i in range(m):
    for j in range(i+1, m):
        Uij = U[i, j]
        Uji = U[j, i]

        if Uij == 0 and Uji == 0:
            relationship = "No Relationship"
        elif Uij > 0 and Uji > 0:
            relationship = "Mutualism"
        elif Uij < 0 and Uji < 0:
            relationship = "Competition"
        else:
            relationship = "Exploitation"

        process_i = process_descriptions[i]
        process_j = process_descriptions[j]

        relationships[f"{process_i} <-> {process_j}"] = relationship

# Print the relationships
for process_pair, relationship in relationships.items():
    print(f"{process_pair}: {relationship}")

Product Manufacturer (1) <-> Service Provider (2): Exploitation
Product Manufacturer (1) <-> User/Consumer (3): Mutualism
Product Manufacturer (1) <-> Collection (EoL) (4): Exploitation
Product Manufacturer (1) <-> Reuse (5): No Relationship
Product Manufacturer (1) <-> Redistribute (EoL) (6): No Relationship
Product Manufacturer (1) <-> Refurbish/Recycle (EoL) (7): No Relationship
Product Manufacturer (1) <-> Ultimate EoL (8): Mutualism
Service Provider (2) <-> User/Consumer (3): Exploitation
Service Provider (2) <-> Collection (EoL) (4): Mutualism
Service Provider (2) <-> Reuse (5): No Relationship
Service Provider (2) <-> Redistribute (EoL) (6): No Relationship
Service Provider (2) <-> Refurbish/Recycle (EoL) (7): No Relationship
Service Provider (2) <-> Ultimate EoL (8): Exploitation
User/Consumer (3) <-> Collection (EoL) (4): Exploitation
User/Consumer (3) <-> Reuse (5): No Relationship
User/Consumer (3) <-> Redistribute (EoL) (6): No Relationship
User/Consumer (3) <-> Refurbish/R

In [35]:
#synergism 
# Calculate the ratio of the sum of positive entries over the sum of negative entries
positive_sum = np.sum(U[U > 0])
negative_sum = np.sum(U[U < 0])

# Avoid division by zero if there are no negative values
if negative_sum != 0:
    syn = positive_sum / abs(negative_sum)
else:
    syn = "Undefined (no negative entries)"

print("Network Synergism:", syn)

Network Synergism: 5.499582888479187


In [36]:
#mutualism
# Calculate the ratio of the number of positive entries over the number of negative entries
positive_count = np.sum(U > 0)
negative_count = np.sum(U < 0)

# Avoid division by zero if there are no negative values
if negative_count != 0:
    mut = positive_count / negative_count
else:
    mut = "Undefined (no negative entries)"

# Print the ratio
print("Network mutualism:", mut)

Network mutualism: 3.6666666666666665


In [37]:
#homogenization

# Function to calculate the coefficient of variation (CV)
def coefficient_of_variation(matrix):
    mean = np.mean(matrix)
    std_dev = np.std(matrix)
    
    if mean != 0:
        cv = std_dev / mean
    else:
        cv = "Undefined (mean is zero)"
    
    return cv

# Calculate the CV for matrices G and N
cv_G = coefficient_of_variation(G)
cv_N = coefficient_of_variation(N)

# Calculate the ratio of CV(G) over CV(N)
if cv_N != 0:
    hom = cv_G / cv_N
else:
    hom = "Undefined (CV(N) is zero)"

# Print the ratio
print("Network Homogenization:", hom)

Network Homogenization: 2.3899419627377902


In [38]:
#Throughflow diversity
FD = 0
epsilon = 1e-10  # A very small number
for i in range(n):
    FD += -((T_i[i] / (TST_flow + epsilon)) * (math.log((T_i[i] + epsilon) / (TST_flow + epsilon), 2)))
print("Flow Diversity:", FD)

Flow Diversity: 2.5112571588852735


## Information Theory 

In [39]:
#Development capacity
DC = 0.0

for i in range(len(R)):
    for j in range(len(R)):
        if i != j:
            DC += -(R[i, j] * np.log2(R[i, j] / TST_put + epsilon))

# Print the ascendancy
print("Development Capacity =", DC)

Development Capacity = 3.3676022192666526


In [40]:
#Ascendency
ASC = 0.0
for i in range(len(R)):
    for j in range(len(R)):
        if i != j:
            numerator = R[i, j]
            denominator = np.sum(R[i, :]+ epsilon) * (np.sum(R[:, j]) + epsilon)
            ASC += numerator * np.log2(((numerator*TST_put) /denominator)+epsilon)
# Print the ascendancy
print("Ascendency =", ASC)

Ascendency = 3.1166390319738335


In [41]:
#Redundancy
PHI = 0.0
for i in range(len(R)):
    for j in range(len(R)):
        if i != j:
            numerator = R[i, j]
            denominator = np.sum(R[i, :]+ epsilon) * (np.sum(R[:, j]) + epsilon)
            PHI += -numerator * np.log2(((numerator**2) /denominator)+epsilon)

# Print the ascendancy
print("Redundancy =", PHI)

Redundancy = 0.25096318733757367


In [42]:
#Ratio of ascendency to development capacity
R_ASC = ASC/DC
print("Relative Ascendency =", R_ASC)

Relative Ascendency = 0.92547718793597


In [43]:
#Internal Development capacity
DC_i = 0.0
for i in range(len(F)):
    for j in range(len(F)):
        if i != j:
            DC_i += -(F[i, j] * np.log2(F[i, j] / TST_put + epsilon))

# Print the ascendancy
print("Internal Development Capacity =", DC_i)

Internal Development Capacity = 2.1948668066776458


In [44]:
#Internal ascendency
ASC_i = 0.0
for i in range(len(F)):
    for j in range(len(F)):
        if i != j:
            numerator = F[i, j]
            denominator = np.sum(F[i, :]+ epsilon) * (np.sum(F[:, j]) + epsilon)
            ASC_i += numerator * np.log2(((numerator*TST_put) /denominator)+epsilon)
# Print the ascendancy
print("Internal Ascendency =", ASC_i)

Internal Ascendency = 2.07021291629873


In [45]:
#Internal Redundancy
PHI_i = 0.0
for i in range(len(F)):
    for j in range(len(F)):
        if i != j:
            numerator = F[i, j]
            denominator = np.sum(F[i, :]+ epsilon) * (np.sum(F[:, j]) + epsilon)
            PHI_i += -numerator * np.log2(((numerator**2) /denominator)+epsilon)

# Print the ascendancy
print("Internal Redundancy =", PHI_i)

Internal Redundancy = 0.12465389060572318


In [46]:
#Internal relative ascendency
R_ASC_i = ASC_i/DC_i
print("Internal Relative Ascendency =", R_ASC_i)

Internal Relative Ascendency = 0.9432066264797163


In [47]:
#Robustness
Rob = -R_ASC*math.log(R_ASC)
print("Robustness =", Rob)

Robustness = 0.07167431716615098


In [48]:
#Internal Robustness
Rob_i = -R_ASC_i*math.log(R_ASC_i)
print("Internal Robustness =", Rob_i)

Internal Robustness = 0.05514920114186145


## Food web specific metrics

In [49]:
#Detritivory to herbivory ratio
#open loop recovery:
openr=np.sum(P)+np.sum(E)
#closed loop recovery"
closer=F[6,0]+F[5,1]+F[4,2]
D_H = (openr+closer)/np.sum(Z)
print("Detritivory to herbivory ratio (D:H) =", D_H)

Detritivory to herbivory ratio (D:H) = 0.0


In [50]:
#Mixed trophic impact
sFi=np.zeros(n,dtype='float64')
for i in range (n):
    for j in range (n):
        sFi[i]=sFi[i]+F[i,j]
sFj=np.zeros(n,dtype='float64')
for j in range (n):
    for i in range (n):
        sFj[j]=sFj[j]+F[i,j]
QQ=np.zeros((n,n),dtype='float64')
for i in range (n):
    for j in range (n):
        QQ[i,j]=(F[i,j]/(sFj[j]+0.001)-F[j,i]/(sFi[j]+0.001))
#mixed trophic impact
#matrix of the net impacts (qij)
M=np.zeros((n,n),dtype='float64')
M=np.linalg.inv(I-QQ)-I
MTI=np.zeros(n,dtype='float64')
for i in range (n):
    for j in range (n):
        if i!=j:
             MTI[i]=MTI[i]+M[i,j]**2 
    MTI[i]=math.sqrt(MTI[i]) 
MTI=MTI.flatten()
print ("mixed trophic impacts =",MTI)

mixed trophic impacts = [0.49 0.48 0.49 0.48 0.   0.   0.   0.49]


### Based on amount of biomass

In [51]:
#Mean trophic level
#Case 1: Stocks=1 for all compartments
m=8
Num=0.0
Denom=0.0
MTL=0.0
#Trophic levels (TL): 1: virgin from external env. 2: manufacturer 3: service provider 4: consumer 5: open loop recycle 6: recycle 7: redistribute 8: reuse 
BLi=[np.sum(Z),T_i[0],T_i[1],T_i[2],np.sum(E),T_i[6],T_i[5],T_i[4]]
TLi=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0,7,8]
for i in range (m):
    Num=Num+BLi[i]*TLi[i]
    Denom=Denom+BLi[i]
MTL=Num/Denom
MTL

2.4478672985781986

In [52]:
#Mean Circularity Level (MCL)
m=8
Num=0.0
Denom=0.0
MTL=0.0
#Circularity Levels (CL): 1: Landfill 2: Energy Recovery/Compost 3: Open-loop recovery 4: Refurbish/Recycle 5: Redistribute 6: Reuse 7: Refuse/Rethink
BLi=[0, #1: Litter
     T_i[7], #2: Landfill
     0, #3: Energy Recovery/Compost
     0, #4: Open-loop Recovery
     0, #5: Refursbish/Recycle
     0, #6: Redistribute
     0, #7: Reuse
     0.8 #8: Refuse/Rethink
    ]
CLi=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
for i in range (m):
    Num=Num+BLi[i]*CLi[i]
    Denom=Denom+BLi[i]
MCL=Num/Denom
MCL

6.747774480712166

In [53]:
(MCL-1)/(8-1)

0.821110640101738

In [54]:
T_i[7]

0.21100000000000002

# Modified (New) Metrics 

In [53]:
#Internal Network Intensity (INI)
INI = TST_flow / T_i[2]
print ("Internal Network Intensity (INI) =", INI)

Internal Network Intensity (INI) = 4.055


In [54]:
#Overall Network Intensity (INI)
ONI = TST_put / T_i[2]
print ("Overall Network Intensity (ONI) =", ONI)

Overall Network Intensity (ONI) = 6.275


In [55]:
#Input Efficiency Indicator
IEFI = T_i[2]/TBI
print ("Input Efficiency Indicator (IEFI) =", IEFI)

Input Efficiency Indicator (IEFI) = 0.9009009009009009


In [56]:
TSTci=np.zeros((n),dtype='float64')
TSTc3=0.0
for i in range (n):
    TSTci[i]=((N[i,i]-1)/N[i,i])*T_i[i]
TSTr=(N[2,2]-1)/(N[2,2]+epsilon)*T_i[2]
L=TSTr/(T_i[0]+T_i[1]+T_i[2]+T_i[3])
print ("Loop Tightness =", L)

Loop Tightness = 0.0
